repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: local
  hooks:
    # Run the linter.
    - id: ruff-sort-imports
      name: ruff Sort Imports
      entry: ruff check --fix --select I
      language: system
      types: [python]
    - id: ruff-lint
      name: ruff lint
      entry: ruff check
      language: system
      types: [python]
    # Run the formatter.
    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: system
      types: [python]
